# Generated by Django 2.2 on 2020-02-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200214_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
